# Generated by Django 3.2.4 on 2021-08-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='paragraph',
            field=models.TextField(max_length=1000),
        ),
    ]
