# Generated by Django 3.2.6 on 2021-08-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_blog_post_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='paragraph',
            field=models.TextField(max_length=10000),
        ),
    ]
